# Generated by Django 4.0.3 on 2022-03-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Images',
            new_name='Product_Image',
        ),
        migrations.RenameModel(
            old_name='Product_Points',
            new_name='Product_Point',
        ),
    ]
