# Generated by Django 4.0.3 on 2022-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_product_images_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_banner',
            field=models.ImageField(upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_baner',
            field=models.ImageField(upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='images/product'),
        ),
    ]
