# Generated by Django 4.0.3 on 2022-03-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_card_banner_alter_product_large_baner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_point',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.product'),
        ),
    ]
