# Generated by Django 4.0.3 on 2022-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_image_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('special_line', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='images/banner')),
            ],
        ),
    ]
