# Generated by Django 4.0.3 on 2022-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='link',
            field=models.CharField(default='/product/zara-pink-shirt', max_length=150),
            preserve_default=False,
        ),
    ]
