# Generated by Django 4.0.3 on 2022-03-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brand_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='link',
        ),
    ]
