# Generated by Django 4.0.3 on 2022-03-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(default='/product/zara-pink-shirt', max_length=150),
            preserve_default=False,
        ),
    ]
