# Generated by Django 4.0.3 on 2022-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_paid_at_order_paid_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
